galaxy_info:
  author: Ivan Gavryushin
  description: Role install vector
  company: keqpup232
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Centos
      versions:
        - 7

  galaxy_tags: []

dependencies: []
