---
- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
    mode: '0755'

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/VKCOM/lighthouse.git'
    dest: /usr/share/nginx/html
    version: "{{ version }}"
  notify:
    - restart nginx